version: "3.1"
services:
  nginx:
    container_name: symfony6_nginx
    image: nginx
    ports:
      - "8082:80"
      - "4431:443"
    volumes:
      - ./logs/nginx-access.log:/var/log/nginx/access.log
      - ./logs/nginx-error.log:/var/log/nginx/error.log
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www/mytest
    depends_on:
      - php-fpm
    networks:
      - mytest

  php-fpm:
    container_name: symfony6_php_fpm
    build: ./php-fpm
    ports:
      - "9081:9000"
    volumes:
      - ../:/var/www/mytest
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    networks:
      - mytest

networks:
  mytest: